# -*- coding: utf-8 -*-
"""numpy(d-31).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EyxmaUw6VKoikSKWG2AtIHyoTdHDbLdU
"""

pip install numpy

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print("1-dim",arr1,sep='\n',end='\n\n')

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2-dim",arr2,sep='\n',end='\n\n')

arr3 = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
print("multi-dim",arr3,sep='\n')

zeros = np.zeros((4,3))
print(zeros)
ones = np.ones((2, 2))
print(ones)
identity = np.eye(4)
print(identity)
full_array = np.full((10, 2),"Booked")
print(full_array)

range_arr = np.arange(10,0,-1)
print(range_arr)



#np.random.seed(40)
rand_arr = np.random.randint(100)
print(rand_arr)
rand_int = np.random.randint(30,60)
print(rand_int)
rand_int = np.random.randint(1, 6, 8)
print(rand_int)
rand_int = np.random.randint(1, 6, (4, 3))
print(rand_int)

rand_float = np.random.rand(10)
print(rand_float)
rand_float = np.random.rand()
print(rand_float)

lang=['html','css','javascript','python','mysql']
rand_choice = np.random.choice(lang, 3)
print(rand_choice)

arr = np.array([[1, 2], [4, 5],[6,7],[8,7],[1,2],[4,5]])
print(arr.shape)
reshaped = arr.reshape(3,4)
print(reshaped)
flattened = arr.flatten()
print(flattened)
transposed = arr.T
print(transposed)

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(matrix[0:3, 0])
print(matrix[0:3, 1])
print(matrix[0:2, 0:2])
print(matrix[1:3,1:3])

arr = np.array([4, 9, 16, 25, 36])
print(arr+10)
print(arr*2)
print(arr**0.5)
print(arr%2==0)
print(arr[arr%2!=0])

a=np.array([1,2,3,4,5])
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.var(a))
print(np.sort(a))

a=np.array([2,4,6,8])
print(np.cumsum(a))
print(np.cumprod(a))

a=np.array([1,1,2,3,4,5,6,2])
un_val=np.unique(a)
print(un_val)
sp_val=np.split(a,2)
print(sp_val)

a=np.array([10,30,40])
v_arr=a.view()
v_arr[0]=11
print(a,v_arr)
c_arr=a.copy()
c_arr[1]=100
print(a,c_arr)

a=np.array([[1,2],[2,3]])
b=np.array([[1,6],[12,3]])
print(np.dot(a,b))