# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12vG06W3-hgH2UZQ1o-Sh9sblft78xly0
"""

import matplotlib.pyplot as plt
hours=[1,2,3,4,5,6,7,8]
visitors=[50,60,65,70,90,120,110,130]
plt.plot(hours,visitors,
         color="blue",
         marker="o",
         linestyle="-",
         linewidth=1,
         alpha=0.5,
         label="Visitors")
plt.title("Website Visitors Per Hour")
plt.xlabel("Hour of Day")
plt.ylabel("Number of Visitors")
plt.legend()
plt.grid(True,linestyle="--",alpha=1)
plt.show()

import matplotlib.pyplot as plt
products=["Laptop","Mobile","Tablet","Headphones","Smartwatch"]
sales=[250,300,400,150,500]
plt.bar(products,sales,color="pink",edgecolor="red",alpha=1,width=0.5)
plt.title("Product Sales Comparision")
plt.xlabel("Products")
plt.ylabel("Units Sold")
plt.show()

import matplotlib.pyplot as plt
marks=[20,25,30,35,40,45,50,55,60,65,
       70,75,80,85,90,95,23,43,53,73,
       15,65,42,76,28,96,54,37,85,19]
plt.hist(marks,bins=7,histtype="bar",color="yellow",edgecolor="pink",density=False)
plt.title("Distribution of Students Marks")
plt.xlabel("Marks Range")
plt.ylabel("Number of students")
plt.show()

import matplotlib.pyplot as plt
brands=["Oneplus","Apple","Oppo","Realme","Others"]
market_share=[25,30,20,15,10]
plt.pie(market_share,
        labels=brands,
        autopct="%.2f%%",
        startangle=90,
        colors=["skyblue","yellow","pink","lightcoral","lightgreen"],
        explode=[0.2,0,0,0,0],
        shadow=True)
plt.title("Mobile Market Share 2026")
plt.show()

import matplotlib.pyplot as plt
ad_spend=[2,4,5,7,8,10,11,12]
sales=[27,25,28,32,37,55,76,87]
profit=[200,150,175,240,480,520,430,580]
colors=[8,1,2,3,5,6,7,4]
plt.scatter(ad_spend,sales,
            s=profit,
            c=colors,
            cmap="Blues",
            alpha=1,
            edgecolor="black",
            linewidth=1)
plt.title("Advertising Spend Vs Sales (with color & size)",fontsize=14,fontweight="bold")
plt.xlabel("Ad Spend ($1000s)",fontsize=12)
plt.ylabel("Sales ($1000s)",fontsize=12)
plt.colorbar(label="Sales Value")
plt.grid(True,linestyle="--",alpha=1)
plt.show()

import matplotlib.pyplot as plt
scores=[[60,65,70,80,2],
        [70,74,80,90,95],
        [35,40,43,54,55],
        [15,20,17,29,95],
        [56,65,64,59,70]
]
plt.boxplot(scores,
            patch_artist=True,
            medianprops=dict(color="yellow",linewidth=1),
            whiskerprops=dict(color="green",linewidth=1),
            capprops=dict(color="black",linewidth=1),
            notch=True,
            vert=True,
            labels=["A","B","C","D","E"])
plt.title("Exam Score Distribution Across Classes")
plt.xlabel("Classes")
plt.ylabel("Scores")
plt.grid(True,linestyle="--",alpha=0.5)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
data=np.array([
    [30,25,35,40,65],
    [33,30,29,27,25],
    [36,32,40,45,23],
    [45,67,98,90,67]
])
days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
weeks=["Week1","Week2","Week3","Week4"]
sns.heatmap(data,
            annot=True,
            fmt=".2f",
            cmap="YlOrRd",
            linewidth=1,
            xticklabels=days,
            yticklabels=weeks)
plt.title("Weekly Temperature Heatmap",fontsize=14,fontweight="bold")
plt.xlabel("Days of the Week")
plt.ylabel("Weeks")
plt.show()

