# -*- coding: utf-8 -*-
"""webScraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tj5KYjlrZ0YD9KyQqbti49kH7mqNVEJs
"""

import requests
from bs4 import BeautifulSoup

url="https://codegnan.com/"

#loading the webpage in memory using request library
page=requests.get(url)

#checking the status of web page
page.status_code

htmlcode=page.text
print(type(htmlcode))

#beautifulsoup is used to convert a string to parser
soup=BeautifulSoup(htmlcode, 'html.parser')
print(soup)

title=soup.title.text
print("website",title)

headings=soup.find_all("h2")

for heading in headings:
  print(heading.text.strip())

links=soup.find_all("a")
for link in links[:5]:
  print(link.get('href'))

images=soup.find_all("img")
for image in images[:5]:
  print(image.get("src"))

description=soup.find("meta",attrs={"name":"description"})
if description:
  print("Description:")
  print(description.get("content"))

scripts=soup.find_all("script")
for script in scripts:
  print(script.get('src'))

og_img=soup.find("meta",property="og:image")
print(og_img["content"])



og_title=soup.find("meta",property="og:title")
print(og_title["content"])

