# -*- coding: utf-8 -*-
"""21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ed_0K5dkgRpOtmugWC_-E0kZvzD1nGGg
"""

import pandas as pd
prices=[20000,30000,4000,50000]
products=["phone","laptop","tab","smartwatch"]
product_prices=pd.Series(prices,index=products)
print(product_prices)

print("mean",product_prices.mean())
print("sum",product_prices.sum())
print("min",product_prices.min())
print("max",product_prices.max())

print(product_prices.head(-1))
print(product_prices.tail(1))

print(product_prices.apply(lambda x:(x+(x*0.18))))
print(product_prices.map(lambda x:f"{x}.00"))

print(product_prices.sort_values())
print(product_prices.sort_index())
print(product_prices.sort_index(ascending=False))
print(product_prices.value_counts())

data={
"products":["phone","laptop","tab","smartwatch"],
"prices":[20000,30000,4000,50000],
"Brand":["oneplus","hp","realme","apple"],
"stock":[30,90,50,40,],
"Bestseller":[True,False,True,False]
}
df=pd.DataFrame(data)
print(df)

from google.colab import files
import pandas as pd
uploaded = files.upload()
df=pd.read_excel("products_50_rows.xlsx")
print(df)

print(df.shape)
print(df.columns)
print(df.info())

print(df.head(4))
print(df.tail(5))

print(df.iloc[4])
print(df.iloc[14])
print(df["Product"])

print(df.loc[2,"Brand"])
print(df.loc[3,"Product"])
print(df.loc[14,"Stock"])
print(df)
print(df.iloc[4,2])
print(df.iloc[3,1])

df_dropped=df.drop(columns=["Stock"])#-it will delete temporarly
#df_dropped=df.drop(columns=["Stock"],inplace=True)-it will delete permemnently
print(df_dropped)

df_rename=df.rename(columns={"Price": "Cost"})
#df_rename=df.rename(columns={"Price": "Cost"},inplace=True)
print(df_rename)

print(df.loc[df["BestSeller"]=="True"])
print(df.loc[df["Price"]<=58000])
print(df.loc[df["Stock"]<=40])

df_groupby=df.groupby("Brand").agg({"Price":"mean","Stock":"mean"})
print(df_groupby)
print(df.groupby("Brand").agg({"Price":["mean","max","min","sum"]}))
print(df.groupby("Brand")["Price"].mean())

data2={
    "Brand":["Soundamax","TechNova","ByteCore","Timetrack","EchoBoom"],
    "rating":[4.2,4.5,4.3,4.8,4.9],
    "discount":[23,28,34,16,15]
}
df_ratings=pd.DataFrame(data2)
print(df_ratings)

df_merged=df.merge(df_ratings,on="Brand")
print(df_merged)

new_data={
    "Product":["Tablate"],
    "Brand":["SmartWare"],
    "Price":[18909],
    "Stcok":[23],
    "BestSeller":[True]
}
df_new=pd.DataFrame(new_data)
print(df_new)

df_concat=pd.concat([df,df_new],ignore_index=True)
print(df_concat)